# Generated by Django 2.2.2 on 2019-06-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='C_purchase_date',
        ),
    ]
