# Generated by Django 2.2.2 on 2019-06-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0003_remove_customer_c_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='C_purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='P date'),
        ),
    ]
