# Generated by Django 2.2.2 on 2019-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0004_customer_c_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='C_return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='P date'),
        ),
    ]
